version: "3"

volumes:
  maildir_vol:

networks:
  mail_vlan:
    driver: bridge

services:
  postfix:
    build: postfix-resources
    image: postfix
    container_name: postfix
    environment:
    ports:
      - "8025:25"
      - "8465:465"
    networks:
      - mail_vlan
    volumes:
      - maildir_vol:/home/sam/Maildir/
    restart: unless-stopped
